First draft: assertions and assessments
BenchLabs/bench-technology-handbook pull request #23
Opened 2022-02-02 20:27 UTC by BlakeTurner

New training module: Assertions and Assessments

2022-02-02 23:23 UTC, dmorgantini commented on assertions-and-assessments.md
> +An **Ungrounded Assessment** is an assessment that has no assertions to back it up. A **Grounded Assessment** is the opposite: a statement that is can be backed up—grounded—by assertions.
something went weird in this sentence

2022-02-02 23:23 UTC, dmorgantini commented on assertions-and-assessments.md
> +- **Grounded:** When you spoke, your heart rate we elevated and your pupils dilated. Therefore, I believe that you're lying.
was

2022-02-15 23:59 UTC, vweller commented on inspiring-action.md
> +The vast majority of the time, when describe the world around us, we are making assessments, not assertions. This is entirely natural—we perceive reality via our uniquely configured senses, and under
"The vast majority of the time, when describe the world around us"
should be:
"he vast majority of the time, when describing the world around us"

2022-02-16 00:08 UTC, vweller commented on inspiring-action.md
> +- 3 and 4 are best practiced in groups—this is a great as a team building exercise.
"this is a great as a team building exercise"
should be:
"this is a great team building exercise" or "this is great as a team building exercise"

2022-02-16 00:09 UTC, vweller requested changes
love the content, just have a couple of typo changes requested.

2022-02-16 00:18 UTC, Seanatbench commented on inspiring-action.md
> +- **Person 1**: They are significantly higher: there's a big, sudden spike.
I think this would read better if you change what comes after the colon to something more measurable. _Big_ and _sudden_ are subjective terms. What about "100 times normal" instead?

2022-02-16 00:24 UTC, Seanatbench commented on inspiring-action.md
> +Note that in the conversations above Person 2 comes across as a leader, and Person 1 doesn't. This is because Person 2 is relentless in gathering assertions before accepting Person 1's assessment. Pe
Person 2 being a leader is your assessment, which you follow-up with assertions. Maybe re-write it to make that explicit or introduce a working definition of a leader to better meet the relevancy condition.

Alternatively, put it to the reader:
"Which of the two people in the script above did you consider a stronger communicator? Which one sounded like a leader? Person 1 would show up very differently if they had grounded their initial assessment:"

2022-02-16 00:32 UTC, Seanatbench commented on inspiring-action.md
> +The line acts as an acid test for the effectiveness of an assessment. If an assessment is made from below the line, it presents a limited view of how things might get better. Therefore, it is unlikel
I suggest removing _acid_ and just saying test. I don't expect all of us will know what an acid test is unless we make Tom Wolfe required reading

2022-02-16 20:16 UTC, BlakeTurner commented on inspiring-action.md
> +The line acts as an acid test for the effectiveness of an assessment. If an assessment is made from below the line, it presents a limited view of how things might get better. Therefore, it is unlikel
Haha, they don't need to read any books. They can google "acid test" and have a satisfying response (a conclusive test of the success or value of something).

2022-02-18 23:37 UTC, Seanatbench commented on inspiring-action.md
> +Assessments can be put into two categories: "open door assessments" and "closed door assessments". An open door assessment is an assessment that describes the world as something ready for change. An
Type: 'An closed door assessment', change to 'A closed door assessment'

2022-02-18 23:49 UTC, Seanatbench commented on inspiring-action.md
> +|This is low quality work.|This is a great first try.|
The first two pairs could be more tightly coupled, particularly in comparison to the last one. Spitballing suggestions:

|This was way harder than we expected so we missed our deadline.|We missed our deadline, but we identified what we need to improve for next time.|
|This is low quality code.|This code will need changes before it's ready.|

2022-02-28 22:51 UTC, vweller approved these changes

2022-02-28 22:53 UTC, vweller approved these changes

2022-02-28 22:57 UTC, vweller approved these changes

2022-02-28 23:32 UTC, merged