revamp how were organized
BenchLabs/bench-technology-handbook pull request #24
Opened 2022-02-03 20:36 UTC by BlakeTurner

2022-02-03 21:10 UTC, vweller commented on how-were-organized.md
> +The Platform team owns our cloud infrastructure, our build pipeline, and our development environment. They play a big role in enabling Product Engineering, IT, and Data with infrastructural support a
The platform team own our cloud infrastructure and builds and maintains the interfaces that Benchmates use to create value for our customers. They play a big role in enabling Product Engineering, IT, and Data with infrastructural support and guidance

2022-02-03 21:14 UTC, vweller commented on how-were-organized.md
> +The DXI team is focused on tools, frameworks, techniques, practices, and systems that help bring joy to the software development experience and to reduce any negative impacts, friction, and pain that
please include "app security" as well. 🙏

2022-02-03 21:14 UTC, vweller requested changes
In the image it says Security for PLA, but it is specifically the infra sec. DXI will be working with App security concerns. Can you please update the image?

2022-02-03 21:47 UTC, vweller approved these changes
Looks great! Thank you!

2022-02-04 19:09 UTC, Seanatbench commented on how-were-organized.md
> +BAS handles all internal and external bug reports, questions, and stakeholder requests. They're also experts in our applications, and regularly provide help and training to unblock other Benchmates.
I'd rewrite as:
BAS triages internal and external bug reports, questions, and stakeholder requests. They're experts in our applications, and regularly provide help and training to empower other Benchmates. Increasingly they're taking on other functions, like QA, site updates, and compliance.

2022-02-04 19:15 UTC, b-drama requested changes

2022-02-04 19:15 UTC, b-drama commented on how-were-organized.md
> +The IT team owns our physical infrastructure (wifi, on-prem VPN, laptops, etc) as well as the access to our software (think Okta, Salesforce, etc). They are also responsible for onboarding, offboardi
The IT team owns and supports our physical infrastructure (wifi, on-prem VPN, laptops, etc) as well as the administrating and maintaining access control to various software. They are also responsible for onboarding, offboarding, and a significant amount of our security controls.

2022-02-04 19:18 UTC, Seanatbench commented on how-were-organized.md
> -### Data
I'd prefer to have a header for Support with BAS and Sup Eng as sub-headers beneath it. We do this in the BizTech documents to show that they're two halves of the support org. Would that formatting overcomplicate what you're trying to do here?

2022-02-04 19:19 UTC, Seanatbench commented on how-were-organized.md
> +The Support Engineering team's primary concern is KTLO in our application level, their secondary concern is supporting stakeholder requests that are "too small for the roadmap", and their tertiary co
Suggestion: 
Support Engineering's primary concern is KTLO in our application, balancing their remaining capacity between supporting stakeholders with features that are too small for the roadmap and innovating to make both KTLO and supporting stakeholders more efficient. Sup Eng and BAS work together to handle crises when they occur, pulling in other BizTech teams or Product Engineering if needed.

2022-02-04 22:42 UTC, b-drama approved these changes

2022-02-04 22:54 UTC, merged